baseURL = "https://www.dgwp.org/"
languageCode = "en-gb"
title = "DGWP"

enableRobotsTXT = true
disableAliases = true
disableKinds = ["taxonomy", "term"]

[params]
images = ["android-chrome-512x512.png"] #img for Open Graph
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "JSON", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "node_modules/bourbon/core/"
    target = "assets/styles/vendors/bourbon"

  [[module.mounts]]
    source = "node_modules/@csstools/normalize.css/"
    target = "assets/styles/vendors/normalize"

  [[module.mounts]]
    source = "node_modules/flexsearch/dist"
    target = "assets/js/vendor/flexsearch"

  [[module.mounts]]
    source = "node_modules/mark.js/dist"
    target = "assets/js/vendor/mark.js"