baseURL: "http://example.com"
languageCode: en-gb
title: ""
copyright: "&copy; {currentYear}"
enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - term

params:
  logo: ""
  disallow_search_engines: false
  matomo:
    url: ""
    siteId: ""

# add JSON, Redirects, Headers
outputs:
  home:
    - HTML
    - JSON
    - REDIRECTS
    - HEADERS

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes:
      - ''
    delimiter: ''

# add output format for netlify _redirects & _headers
outputFormats:
  REDIRECTS:
    mediatype: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true

# toc settings
markup:
  tableOfContents:
    endLevel: 2
    ordered: true
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    style: bw

module:
  imports:
  - path: "github.com/feathericons/feather"
    mounts:
    - source: icons
      target: assets/img/icons

security:
  # babel is not allowed by default
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^babel$
