[build]
    command = "npm run ci --buildURL=$URL"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.87.0"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "npm run ci --buildURL=$DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "npm run ci --buildURL=$DEPLOY_PRIME_URL"
