baseURL: "http://example.com"
languageCode: en-gb
title: "W210"
copyright: "&copy; {currentYear}"
enableRobotsTXT: false
disableAliases: true
disableKinds:
  - taxonomy
  - term
paginate: 5

menu:
  home:
  - name: Docs
    url: "/docs/"
    Params:
      class: button--primary
  - name: Source
    url: "https://github.com/paulHasselkuss/W210"

params:
  _merge: shallow

outputs:
  _merge: shallow

mediaTypes:
  _merge: shallow

outputFormats:
  _merge: shallow

markup:
  _merge: shallow

security:
  _merge: shallow

module:
  imports:
  # This is replaced in go.mod to point to the parent directory
  - path: "github.com/paulHasselkuss/W210"